#!/bin/sh /etc/rc.common
# Copyright (C) 2018 Mikael Magnusson

START=15

log_output() {
	logger -t container_init "$@"
}

boot() {
	# Only execute for lxc containers
	if [ "$container" != "lxc" ]; then
		exit 0
	fi

	if [ ! -e /lib/modules/$(uname -r) ]; then
		local modulesdir=$(basename $(dirname $(apk info -L kmod-nft-core|grep "lib/modules/[0-9].*"|head -1)))
		ln -s $modulesdir /lib/modules/$(uname -r)
	fi
	exit $res
}
